TestSolution/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoRepository;
using TestSolution.Data;
using TestSolution.Rabbit;

namespace TestSolution.Controllers
{
    public class ClaimController : BaseController
    {
        static MongoRepository<Claim> claimrepo = new MongoRepository<Claim>();

        // will return the claim for current user, or else return null
        public Claim getMyClaim()
        {
            try
            {
                string user = User.Identity.Name.ToLower();
                //we want to correct for user names in the form AA\tpmurphy
                if (user.Contains("\\"))
                {
                    user = user.Substring(3);
                }

                Claim claim = claimrepo.First(c => c.EmpInfo.LanId.ToLower() == user);

                return claim;
            }
            catch
            {
                return null;
            }
        }
        
        //
        // GET: /Claim/
        public ActionResult Index()
        {
            return View(claimrepo);
        }

        //
        // GET: /Claim/Details/5
        [AllowAnonymous]
        public ActionResult Details(string id)
        {
            Claim claim = claimrepo.GetById(id);

            ViewBag.flash = TempData["flash"];

            bool isAdmin = isInRole(User.Identity.Name, "Admin");
            ViewBag.isAdmin = isAdmin;

            if (isAdmin)
            {
                //we need to set to ViewBag properties to have the delete button work
                ViewBag.id = id;
                //ViewBag.controller = "Template";
                ViewBag.controller = RouteData.Values["controller"].ToString();
            }

            return View(claim);
        }
        //
        //GET: /Claim/Create
        public ActionResult Create()
        {
            return View(
                new Claim() { }

            );
        }

        //
        // POST: /Claim/Create
        // Would have prefered using [AllowHTML] on just the body, rather than disabling validation for this action
        // but as this action is an admin only action, we should be OK
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Claim claim)
        {
            try
            {

                claimrepo.Add(claim);

                //now log it
                bool logged = logAction("Created Claim " + claim.EmpInfo.EmpId, "Informational");

                TempData["flash"] = buildFlash("success", "Claim Created", "Claim has been created");

                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.flash = buildFlash("danger", "Error", "Error Creating Claim");

                return View();
            }
        }



        //
        // GET: /Claim/Edit/5
        public ActionResult Edit(string id)
        {
            Claim claim = claimrepo.GetById(id);

            return View(claim);
        }
        //
        // POST: /Claim/Edit/5
        [HttpPost]
        public ActionResult Edit(Claim claim)
        {
            try
            {
                claimrepo.Update(claim);

                //now log it
                bool logged = logAction("Updated Claim " + claim.EmpInfo.EmpId, "Informational");

                TempData["flash"] = buildFlash("success", "Claim Updated", "Claim has been updated");

                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.flash = buildFlash("danger", "Error", "Error Updating Claim");

                return View();
            }
        }


        //
        // POST: /Claim/Delete/5
        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                string comment = "";
                if (isInRole(User.Identity.Name, "Admin"))
                {
                    Claim claim = claimrepo.GetById(id);
                    string title = claim.EmpInfo.DisplayName;

                    claimrepo.Delete(id);
                    //now log this          
                    comment = "The claim for " + title + " has been deleted";
                    logAction(comment, "Informational");

                    TempData["flash"] = buildFlash("success", "Claim Deleted", comment);

                    return RedirectToAction("Index");
                }
                else
                {
                    comment = "You have insufficient rights to delete this template";
                    logAction(comment, "Warning");
                    TempData["flash"] = buildFlash("warning", "Insufficient Rights", comment);

                    return RedirectToAction("Index");
                }
            }
            catch
            {
                string comment = "Error deleting claim";
                logAction(comment, "Error");
                TempData["flash"] = buildFlash("danger", "Error", comment);

                return RedirectToAction("Index");

            }
        }
    }
}

TestSolution/Controllers/ProfileInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestSolution.Controllers
{
    public class ProfileInfoController : Controller
    {
        //
        // GET: /ProfileInfo/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /ProfileInfo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /ProfileInfo/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ProfileInfo/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ProfileInfo/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /ProfileInfo/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ProfileInfo/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /ProfileInfo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TestSolution/Controllers/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoRepository;
using TestSolution.Data;
using TestSolution.Rabbit;

namespace TestSolution.Controllers
{
    public class TemplateController : BaseController
    {

        static MongoRepository<Template> templaterepo = new MongoRepository<Template>();
        //
        // GET: /Template/
        public ActionResult Index()
        {
            return View(templaterepo);
        }

        //
        // GET: /Template/Details/5
        [AllowAnonymous]
        public ActionResult Details(string id)
        {
            Template template = templaterepo.GetById(id);

            ViewBag.flash = TempData["flash"];

            bool isAdmin = isInRole(User.Identity.Name, "Admin");
            ViewBag.isAdmin = isAdmin;

            if (isAdmin)
            {
                //we need to set to ViewBag properties to have the delete button work
                ViewBag.id = id;
                //ViewBag.controller = "Template";
                ViewBag.controller = RouteData.Values["controller"].ToString();
            }

            return View(template);
        }

        // GET: /Template/Display/xxxx
        // similar to read, but getting by key, and displaying in a slightly different way
        [AllowAnonymous]
        public ActionResult Display(string id)
        {
            Template template = null;

            ViewBag.isAdmin = isInRole(User.Identity.Name, "Admin");

            if (templaterepo.Exists(c => c.Key == id))
            {
                template = templaterepo.First(c => c.Key == id);

                ViewBag.flash = TempData["flash"];
            }
            else
            {
                template = new Template()
                {
                    Subject = id,
                    Key = id,
                    Body = "The page for this key does not yet exist"
                };

                ViewBag.flash = buildFlash("warning", "Page does not exist", "A page for this key does not yet exist.  Please contact your admin.");
            }

            return View(template);
        }



        //
        //GET: /Template/Create
        public ActionResult Create()
        {
            return View(
                new Template() { }

            );
        }

        //
        // POST: /Template/Create
        // Would have prefered using [AllowHTML] on just the body, rather than disabling validation for this action
        // but as this action is an admin only action, we should be OK
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Template template)
        {
            try
            {

                templaterepo.Add(template);

                //now log it
                bool logged = logAction("Created Template " + template.Key, "Informational");

                TempData["flash"] = buildFlash("success", "Template Created", "Template has been created");

                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.flash = buildFlash("danger", "Error", "Error Creating Template");

                return View();
            }
        }


        //
        //GET: /Template/Edit/id
        public ActionResult Edit(string id)
        {
            Template template = templaterepo.GetById(id);

            return View(template);
        }

        //
        // POST: /Template/Edit
        // Would have prefered using [AllowHTML] on just the body, rather than disabling validation for this action
        // but as this action is an admin only action, we should be OK
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Edit(Template template)
        {
            try
            {
                templaterepo.Update(template);

                //now log it
                bool logged = logAction("Updated Template " + template.Key, "Informational");

                TempData["flash"] = buildFlash("success", "Template Updated", "Template has been updated");

                return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.flash = buildFlash("danger", "Error", "Error Updating Template");

                return View();
            }
        }


        //
        // POST: /Template/Delete
        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                string comment = "";
                if (isInRole(User.Identity.Name, "Admin"))
                {
                    Template template = templaterepo.GetById(id);
                    string title = template.Key;

                    templaterepo.Delete(id);
                    //now log this          
                    comment = "The " + title + " template has been deleted";
                    logAction(comment, "Informational");

                    TempData["flash"] = buildFlash("success", "Template Deleted", comment);

                    return RedirectToAction("Index");
                }
                else
                {
                    comment = "You have insufficient rights to delete this template";
                    logAction(comment, "Warning");
                    TempData["flash"] = buildFlash("warning", "Insufficient Rights", comment);

                    return RedirectToAction("Index");
                }
            }
            catch
            {
                string comment = "Error deleting template";
                logAction(comment, "Error");
                TempData["flash"] = buildFlash("danger", "Error", comment);

                return RedirectToAction("Index");

            }
        }

    }
}

TestSolution/Views/Shared/Save_Layout.cshtml
@{
    ViewBag.Title = "Save_Layout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Save_Layout</h2>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Hello, @User.Identity.Name!</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TestSolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Public Transit Subsidy Program</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/dojo/1.10.0/dijit/themes/claro/claro.css" />

    @RenderSection("head", required: false)

    <!-- was script src="~/Scripts/modernizr-2.6.2.js -->
</head>
<body class="claro">
    @RenderPage("~/Views/Shared/_navigator.cshtml")

    @RenderSection("breadcrumbs", required: false)

    <div class="container body-content">
        <div id="flash-placeholder"></div>

        @if (ViewBag.flash != null)
        {
                <!-- hide for now as we are adding flash via js - see scripts below -->
            <div class="hide alert alert-dismissable alert-@ViewBag.flash.type">
                <button class="close" data-dismiss="alert" type="button">x</button>
                <h4>@ViewBag.flash.title</h4>
                <p>@ViewBag.flash.body</p>
            </div>
        }

        <div class="row">
            @RenderBody()
        </div>

        <div id="logwrap"></div>

        <hr />

        <footer id="page-footer" class="row">
            <p id="page-footer-copy">&copy; @DateTime.Now.Year - U.S. Environmental Protection Agency, Region 2 </p>
        </footer>

    </div>

    <!-- scripts at bottom  -->
    <script type="text/javascript">
        //dojoConfig must be in place before dojo is loaded
        //use.js allows us to require non AMD packages as if they were AMD
        //paths and use are for non-amd packages
        //packages are for AMD packages
        //aliases are for amd single files
        //for applicationPath to work both local and on server, we need to make some adjustments

        var appPath = "@Request.ApplicationPath";
        if (appPath.slice(-1) != "/") {
            appPath += "/";
        }

        //note the subtle difference between dojoConfi.app.path and dojoConfig.request.applicationPath
        var dojoConfig = {
            async: true,
            parseOnLoad: false,
            app: {
                    userName: '@User.Identity.Name.Replace("AA\\", "")',
                    path: appPath,
                    flash: null
                },
                request: {
                    applicationPath: "@Request.ApplicationPath",
                    path: "@Request.Path",
                    queryString: "@Request.QueryString"
                },
                packages: [
                    //amd packages
                    { name: "r2", location: "//x0202tnythnetdv.aa.ad.epa.gov/common/r2commonscripts" },
                    { name: "TestSolution", location: appPath + "Scripts/app" },
                    { name: "test", location: appPath + "Scripts/test" },
                    //{ name: "lodash", location: "//x0202tnythnetdv.aa.ad.epa.gov/common/js/lodash-amd" },
                    { name: "lodash", location: "//cdn.rawgit.com/lodash/lowdash-amd/2.4.1" },
                    //{ name: "dgrid", location: "//x0202tnythnetdv.aa.ad.epa.gov/common/js/dgrid" },
                    { name: "dgrid", location: "//cdn.rawgit.com/SitePen/dgrid/v0.3.16" },
                    //{ name: "xstyle", location: "//x0202tnythnetdv.aa.ad.epa.gov/common/js/xstyle" },
                    { name: "xstyle", location: "//cdn.rawgit.com/kriszyp/xstyle/v0.2.1" },
                    //{ name: "put-selector", location: "//x0202tnythnetdv.aa.ad.epa.gov/common/js/put-selector" }
                    { name: "put-selector", location: "//cdn.rawgit.com/kriszyp/put-selector/v0.3.6" }
                ],
                paths: {
                    "use": "//cdnjs.cloudflare.com/ajax/libs/use.js/0.2.0/use.min",
                    "text": "//cdnjs.cloudflare.com/ajax/libs/require-text/2.0.12/text.min",
                    "typeahead": "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.10.4/typeahead.bundle.min",
                    "signature_pad": "//cdnjs.cloudflare.com/ajax/libs/signature_pad/1.3.2/signature_pad.min",
                    "tinymce": "//tinymce.cachefly.net/4.0/tinymce.min",
                    //"bootstrap": "//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min",
                    //"bootstrap-datepicker": "//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min",
                    "hogan": "//cdnjs.cloudflare.com/ajax/libs/hogan.js/3.0.0/hogan.min.amd",
                    //"jquery": "//code.jquery.com/jquery-1.11.1.min",
                    //"jquery-ui": "//code.jquery.com/ui/1.11.2/jquery-ui.min",
                    "jquery-validate": "//ajax.aspnetcdn.com/ajax/jquery.validate/1.12.0/jquery.validate",
                    "jquery-validate-unobtrusive": "//ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.min"
                },
                aliases: [
                    //["hogan", "//cdnjs.cloudflare.com/ajax/libs/hogan.js/3.0.0/hogan.min.amd.js"],
                    //["jquery", "//code.jquery.com/jquery-1.11.1.min.js"], //should this be in paths?
                    //["jquery-ui", "//code.jquery.com/ui/1.11.2/jquery-ui.min.js"], //should this be in paths?
                    ["stacktrace", "//rawgithub.com/stacktracejs/stacktrace.js/master/stacktrace.js"]
                ],
                use: {
                    "typeahead": { attach: "Typeahead" },
                    "signature_pad": { attach: "SignaturePad" },
                    "tinymce": { attach: "tinymce" },
                    /*
                    "bootstrap": {
                        attach: "bootstrap",
                        deps: ["jquery"]
                    },
                    "bootstrap-datepicker": {
                        attach: "bootstrap-datepicker",
                        deps: ["bootstrap"]
                    },
                    */
                    "jquery-validate": {
                        deps: ["jquery"],
                        exports: "jquery.validation"
                    },
                    "jquery-validate-unobtrusive": {
                        deps: ["jquery"]
                    }
                }
            };
    </script>

    @if (ViewBag.flash != null)
    {
        <script>
            //better way to get ViewBag.flash into a js object?
            dojoConfig.app.flash = {
                title: "@ViewBag.flash.title",
                flashClass: "@ViewBag.flash.type",
                body: "@ViewBag.flash.body"
            };
        </script>
    }

    <script src="//ajax.googleapis.com/ajax/libs/dojo/1.10.1/dojo/dojo.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <!-- should really include the datepicker only where needed -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.min.js"></script>

    <script type="text/javascript">
        //from lodash test2
        function startsWith(string, target, position) {
            string = string == null ? '' : String(string);
            position = typeof position == 'undefined' ? 0 : nativeMin(position < 0 ? 0 : (+position || 0), string.length);
            return string.lastIndexOf(target, position) == position;
        }

        //using html5 webstorage's sessionStorage Object to determine we need to show the warning banner
        if (! sessionStorage.warningBanner) {
            //we need to show the banner
            //this should be written as a widget and only loaded when needed.
            //alert("show banner");
            //if they accept the warning, set sessionStorage.warningBanner to true so they don't see it again this session.
            //sessionStorage.warningBanner = true;
        }

        //define a single global for the application
        var app = {};
        //bootstrap datepicker should be required where actually needed, not global
        require(["TestSolution/applicationClass", "dojo/domReady!"], function (appController) {
            var viewBagIsAdmin = "@ViewBag.isAdmin";
            var isAdmin = (viewBagIsAdmin == "True");

            app = new appController(isAdmin);

            app.username = dojoConfig.app.userName;

            //if we have a flash waiting in ViewBag, go ahead and show it
            //or are we doing this through the section above?
            if (dojoConfig.app.hasOwnProperty('flash')) {
                //app.createFlash(targetnode, dojoConfig.app.flash.type, dojoConfig.app.flash.title, dojoConfig.app.flash.body);
                app.createFlash("flash-placeholder", dojoConfig.app.flash);
            }

            //now test the connectr2 stuff
           // var cr2 = new ConnectR2();
            //cr2.processSelector();


        });



    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

TestSolution/Views/Shared/_navigator.cshtml
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            @Html.ActionLink("TestSolution", "Index", "Home", new { }, new { @class = "navbar-brand" })
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav" id="navlist">
                <li class="dropdown hide" id="navlist_item_Admin">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="adminNav">Admin <span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="adminNav">
                        <li>@Html.ActionLink("Templates", "Index", "Template")</li>
                        <li>@Html.ActionLink("Roles", "Index", "Role")</li>
                    </ul>
                </li>

                <li class="dropdown hide" id="navlist_item_ParkingTags">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="tagNav">Questionnaires <span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="tagNav">
                        <li>
                            @Html.ActionLink("All", "Index", "Questionnaire")
                        </li>
                        <li>
                            @Html.ActionLink("All", "Index", "Claim")
                        </li>
                        <li>
                            @Html.ActionLink("All", "Index", "Certification")
                        </li>
                        <li>
                            @Html.ActionLink("All", "Index", "ProfileInfo")
                        </li>
                   </ul>
                </li>

                <li>
                    @Html.ActionLink("My Questionnaire", "MyQuestionnaire", "Questionnaire")
                </li>
            </ul>

            <form id="nav-tag-finder" class="navbar-form navbar-left hide">
                <input type="text" placeholder="Find Tag" class="form-control tag-finder-typeahead col-lg-8">
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="userNameNav">Hello, <span class="username">@User.Identity.Name</span>! <span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="userNameNav">
                        <li>@Html.ActionLink("About", "Display", "Template", new { id = "About" }, null)</li>
                        <li>@Html.ActionLink("Contact", "Display", "Template", new { id = "Contact" }, null)</li>
                        <li>@Html.ActionLink("Using", "Display", "Template", new { id = "Using" }, null)</li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</div>